package com.mephala.sanayiBackup.main;

import com.mephala.sanayiBackup.exception.SanayiBackupException;
import com.mephala.sanayiBackup.props.PropertyReader;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.util.Calendar;
import java.util.List;

/**
 * Created by Mephalay on 11/12/2016.
 */
public class Main {


    public static void main(String[] args) {
        System.out.println("Running...");
        Calendar calendar = Calendar.getInstance();
        StringBuilder backupFolderNameBuilder = new StringBuilder();
        backupFolderNameBuilder.append(calendar.get(Calendar.DAY_OF_MONTH));
        backupFolderNameBuilder.append(calendar.get(Calendar.MONTH));
        backupFolderNameBuilder.append(calendar.get(Calendar.YEAR));
        String backupFolderName = backupFolderNameBuilder.toString() + "_autoGeneratedSave";
        try {
            PropertyReader propertyReader = PropertyReader.getInstance();
            String backupFolder = propertyReader.getProperty("targetFolder");
            File backupFolderSaveOld = new File(backupFolder + File.separator + backupFolderName);
            if (!backupFolderSaveOld.mkdir()) {
                throw new Exception("Can't create save Old backup");
            }
            File backupFolderFile = new File(backupFolder);
            File[] subFiles = backupFolderFile.listFiles();
            for (File subFile : subFiles) {
                if (subFile.getName().contains("_autoGeneratedSave")) {
                    continue;
                }
                FileUtils.copyFile(subFile, new File(backupFolder + File.separator + subFile));
                if (subFile.isDirectory())
                    FileUtils.deleteDirectory(subFile);
                if (subFile.isFile())
                    subFile.delete();
            }
            subFiles = backupFolderFile.listFiles();
            for (File subFile : subFiles) {
                if (subFile.getName().contains("_autoGeneratedSave") && !subFile.getName().equals(backupFolderName)) {
                    FileUtils.deleteDirectory(subFile);
                }
            }


            List<String> targetFileNames = propertyReader.getProperties("backupFolders");
            for (String targetFileName : targetFileNames) {
                File targetFolder = new File(targetFileName);
                File backUpFolderSaveDirectory = new File(backupFolder + File.separator + targetFolder.getName());
                backUpFolderSaveDirectory.mkdir();
                String backupTargetPath = backUpFolderSaveDirectory.getAbsolutePath();
                File[] targetSubFiles = targetFolder.listFiles();
                for (File targetSubFile : targetSubFiles) {
                    if (targetSubFile.isDirectory()) {
                        FileUtils.copyDirectory(targetSubFile, new File(backupTargetPath + File.separator + targetSubFile.getName()));
                    }
                    if (targetSubFile.isFile()) {
                        FileUtils.copyFile(targetSubFile, new File(backupTargetPath + File.separator + targetSubFile.getName()));
                    }
                }
            }
        } catch (SanayiBackupException sbe) {
            sbe.printStackTrace();
            new RuntimeException("Failed with sbe");

        } catch (Throwable t) {
            t.printStackTrace();
            new RuntimeException("Failed with unknown cause");
        }

    }
}
